// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIX3PjlpLaq0bMkc7bb0A_7VjtpYM-SRw',
    appId: '1:541226579292:web:57dc5ff747467036b1fd99',
    messagingSenderId: '541226579292',
    projectId: 'my-firebaseandroid-projecr01',
    authDomain: 'my-firebaseandroid-projecr01.firebaseapp.com',
    storageBucket: 'my-firebaseandroid-projecr01.appspot.com',
    measurementId: 'G-WX6FDCLRTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxFFgN1bapoyocy-zAEM_Ujw_RbDrxwak',
    appId: '1:541226579292:android:cb153ee802778b12b1fd99',
    messagingSenderId: '541226579292',
    projectId: 'my-firebaseandroid-projecr01',
    storageBucket: 'my-firebaseandroid-projecr01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA33D8TX2hBOLrcNlAzKeQdgKTAog4iGXo',
    appId: '1:541226579292:ios:cf75ec1d43ea1a17b1fd99',
    messagingSenderId: '541226579292',
    projectId: 'my-firebaseandroid-projecr01',
    storageBucket: 'my-firebaseandroid-projecr01.appspot.com',
    iosClientId: '541226579292-4bfet7hhs27c0b99egtos26sbdl35tju.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAndroidapp04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA33D8TX2hBOLrcNlAzKeQdgKTAog4iGXo',
    appId: '1:541226579292:ios:cf75ec1d43ea1a17b1fd99',
    messagingSenderId: '541226579292',
    projectId: 'my-firebaseandroid-projecr01',
    storageBucket: 'my-firebaseandroid-projecr01.appspot.com',
    iosClientId: '541226579292-4bfet7hhs27c0b99egtos26sbdl35tju.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAndroidapp04',
  );
}
